version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user_guiapress
      - MYSQL_PASSWORD=guiapress123
      - MYSQL_DATABASE=guiapress
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 